import { MODULE_ID } from "../constants.js";

export const getThemes = () => ({
	iron: {
		label: "IBHUD.Config.Themes.Iron",
		defaults: {
			scale: 1.0,
			barsX: 0,
			barsY: 0,
			nameX: 0,
			nameY: 0,
			nameZ: 5,
			nameScale: 1.0,
			dotsX: 0,
			dotsY: 0,
			conditionsZ: 5,
			barsZ: 5,
			dotsZ: 5,
			numbersZ: 5,
			badgesZ: 150,
			format: "box",
		},
	},
	glass: {
		label: "IBHUD.Config.Themes.Glass",
		defaults: {
			scale: 1.1,
			barsX: 0,
			barsY: 0,
			nameX: 0,
			nameY: 0,
			nameZ: 5,
			portraitX: 0,
			portraitY: 0,
			dotsX: 0,
			dotsY: 0,
			conditionsZ: 5,
			barsZ: 5,
			dotsZ: 5,
			numbersZ: 5,
			badgesZ: 150,
			format: "box",
		},
	},
	fantasy: {
		label: "IBHUD.Config.Themes.Fantasy",
		defaults: {
			scale: 1.0,
			barsX: 0,
			barsY: 0,
			nameX: 0,
			nameY: 0,
			nameZ: 5,
			dotsX: 0,
			dotsY: 0,
			conditionsZ: 5,
			barsZ: 5,
			dotsZ: 5,
			numbersZ: 5,
			badgesZ: 150,
			x: 0,
			y: 0,
		},
	},
	cyberpunk: {
		label: "IBHUD.Config.Themes.Cyberpunk",
		defaults: {
			scale: 1.0,
			barsX: 0,
			barsY: 0,
			nameX: 0,
			nameY: 0,
			nameZ: 5,
			dotsX: 0,
			dotsY: 0,
			conditionsZ: 20,
			barsZ: 5,
			dotsZ: 5,
			numbersZ: 5,
			badgesZ: 150,
			format: "box",
		},
	},
	medieval: {
		label: "IBHUD.Config.Themes.Medieval",
		defaults: {
			scale: 1.0,
			barsX: 0,
			barsY: 0,
			nameX: 0,
			nameY: 0,
			nameZ: 5,
			dotsX: 0,
			dotsY: 0,
			conditionsZ: 5,
			barsZ: 5,
			dotsZ: 5,
			numbersZ: 5,
			badgesZ: 150,
			x: 0,
			y: 0,
		},
	},
	zenith: {
		label: "IBHUD.Config.Themes.Zenith",
		defaults: {
			scale: 1.0,
			barsX: 0,
			barsY: 0,
			nameX: 0,
			nameY: 0,
			nameZ: 5,
			dotsX: 0,
			dotsY: 0,
			conditionsZ: 8,
			barsZ: 5,
			dotsZ: 5,
			numbersZ: 5,
			badgesZ: 150,
			format: "box",
		},
	},
	rift: {
		label: "IBHUD.Config.Themes.Rift",
		defaults: {
			scale: 1.0,
			barsX: 0,
			barsY: 0,
			nameX: 0,
			nameY: 0,
			nameZ: 5,
			dotsX: 0,
			dotsY: 0,
			conditionsZ: 5,
			barsZ: 5,
			dotsZ: 5,
			numbersZ: 5,
			badgesZ: 150,
			format: "box",
		},
	},
	image: {
		label: "IBHUD.Config.Themes.Image",
		defaults: {
			scale: 1.0,
			barsX: 0,
			barsY: 0,
			nameX: 0,
			nameY: 0,
			nameZ: 5,
			dotsX: 0,
			dotsY: 0,
			conditionsZ: 5,
			barsZ: 5,
			dotsZ: 5,
			numbersZ: 5,
			badgesZ: 150,
			x: 0,
			y: 0,
			format: "popout",
		},
	},
});
