import { MODULE_ID } from "../constants.js";

/**
 * Theme registry and visual metadata for Nik's Action HUD.
 * Exclusively designed for Foundry V14.
 */
export const THEMES = Object.freeze({
	rift: {
		id: "rift",
		label: "NIKS_ACTION_HUD.Themes.Rift",
		defaultLabel: "Rift",
		badge: "Default",
		description: "Modern cosmic dark glass with cyan luminescence",
		colors: {
			bg: "#0b121e",
			surface: "rgba(14, 28, 48, 0.8)",
			border: "#00e5ff",
			accent: "#38bdf8",
			text: "#e2f1ff",
		},
		icon: "fas fa-meteor",
	},
	iron: {
		id: "iron",
		label: "NIKS_ACTION_HUD.Themes.Iron",
		defaultLabel: "Iron",
		description: "Heavy plate, riveted metallic surfaces, crimson accents",
		colors: {
			bg: "#18181b",
			surface: "rgba(39, 39, 42, 0.85)",
			border: "#e61c34",
			accent: "#ef4444",
			text: "#fafafa",
		},
		icon: "fas fa-shield-halved",
	},
	glass: {
		id: "glass",
		label: "NIKS_ACTION_HUD.Themes.Glass",
		defaultLabel: "Glass",
		description: "Translucent frosted glass with soft glow reflections",
		colors: {
			bg: "rgba(15, 23, 42, 0.65)",
			surface: "rgba(255, 255, 255, 0.08)",
			border: "rgba(255, 255, 255, 0.25)",
			accent: "#a5b4fc",
			text: "#ffffff",
		},
		icon: "fas fa-cube",
	},
	fantasy: {
		id: "fantasy",
		label: "NIKS_ACTION_HUD.Themes.Fantasy",
		defaultLabel: "Fantasy",
		description: "Ornate filigree, parchment tones, and burnished gold trims",
		colors: {
			bg: "#1c140e",
			surface: "rgba(44, 30, 20, 0.85)",
			border: "#c59b27",
			accent: "#eab308",
			text: "#fef08a",
		},
		icon: "fas fa-wand-magic-sparkles",
	},
	cyberpunk: {
		id: "cyberpunk",
		label: "NIKS_ACTION_HUD.Themes.Cyberpunk",
		defaultLabel: "Cyberpunk",
		description: "High-contrast neon edges, angled tech lines, and bright grid pulses",
		colors: {
			bg: "#050505",
			surface: "rgba(10, 10, 20, 0.9)",
			border: "#00f0ff",
			accent: "#ff0055",
			text: "#f0fdf4",
		},
		icon: "fas fa-microchip",
	},
	medieval: {
		id: "medieval",
		label: "NIKS_ACTION_HUD.Themes.Medieval",
		defaultLabel: "Medieval",
		description: "Wrought iron, dark weathered timber, and warm embers",
		colors: {
			bg: "#15110e",
			surface: "rgba(35, 25, 18, 0.85)",
			border: "#854d0e",
			accent: "#d97706",
			text: "#fed7aa",
		},
		icon: "fas fa-dungeon",
	},
	zenith: {
		id: "zenith",
		label: "NIKS_ACTION_HUD.Themes.Zenith",
		defaultLabel: "Zenith",
		description: "Clean minimalist layout, floating modern cards, and maximum legibility",
		colors: {
			bg: "#0f172a",
			surface: "rgba(30, 41, 59, 0.85)",
			border: "#64748b",
			accent: "#818cf8",
			text: "#f8fafc",
		},
		icon: "fas fa-layer-group",
	},
	arcanum: {
		id: "arcanum",
		label: "NIKS_ACTION_HUD.Themes.Arcanum",
		defaultLabel: "Arcanum",
		badge: "New",
		description: "Astral high magic with celestial velvet and gold-leaf filigree",
		colors: {
			bg: "#080914",
			surface: "#140f26",
			border: "#d4af37",
			accent: "#f59e0b",
			text: "#f8fafc",
		},
		icon: "fas fa-wand-sparkles",
	},
	obsidian: {
		id: "obsidian",
		label: "NIKS_ACTION_HUD.Themes.Obsidian",
		defaultLabel: "Obsidian",
		badge: "New",
		description: "Tactical solid deep onyx with specular borders and mint accents",
		colors: {
			bg: "#05070a",
			surface: "#0d1117",
			border: "#10b981",
			accent: "#34d399",
			text: "#ffffff",
		},
		icon: "fas fa-gem",
	},
	grimoire: {
		id: "grimoire",
		label: "NIKS_ACTION_HUD.Themes.Grimoire",
		defaultLabel: "Grimoire",
		badge: "New",
		description: "Aged dark parchment, hammered forged iron, and candlelit amber",
		colors: {
			bg: "#0e0a07",
			surface: "#1c1510",
			border: "#4d3522",
			accent: "#f59e0b",
			text: "#fef3c7",
		},
		icon: "fas fa-book-skull",
	},
	eldritch: {
		id: "eldritch",
		label: "NIKS_ACTION_HUD.Themes.Eldritch",
		defaultLabel: "Eldritch",
		badge: "New",
		description: "Abyssal cosmic horror with black chitin and bioluminescent cyan",
		colors: {
			bg: "#03060a",
			surface: "#080d14",
			border: "#06b6d4",
			accent: "#d946ef",
			text: "#e0f2fe",
		},
		icon: "fas fa-eye",
	},
	valiant: {
		id: "valiant",
		label: "NIKS_ACTION_HUD.Themes.Valiant",
		defaultLabel: "Valiant",
		badge: "New",
		description: "Chivalric polished plate steel with royal sapphire and tournament gold",
		colors: {
			bg: "#070c16",
			surface: "#0e1829",
			border: "#94a3b8",
			accent: "#3b82f6",
			text: "#f8fafc",
		},
		icon: "fas fa-shield",
	},
});

export const getThemes = () => THEMES;

export const DEFAULT_ANCHOR_POSITIONS = Object.freeze({
	bottomRight: { anchorX: "right", anchorY: "bottom", label: "Bottom Right" },
	bottomLeft: { anchorX: "left", anchorY: "bottom", label: "Bottom Left" },
	topRight: { anchorX: "right", anchorY: "top", label: "Top Right" },
	topLeft: { anchorX: "left", anchorY: "top", label: "Top Left" },
});
